In [1]:
ma_liste=[1,2,3,4,5,6,7,8,"hello",10.5]

In [2]:
print(ma_liste)

[1, 2, 3, 4, 5, 6, 7, 8, 'hello', 10.5]


In [15]:
ma_liste[1]

2

In [16]:
ma_liste[2:4]

[3, 4]

In [17]:
ma_liste[:4]

[1, 2, 3, 4]

In [18]:
ma_liste[3:]

[4, 5, 6, 7, 8, 'hello', 10.5]

In [19]:
ma_liste[0:2],ma_liste[4],ma_liste[5:7]

([1, 2], 5, [6, 7])

In [20]:
ma_liste[-2]

'hello'

In [21]:
ma_liste[1:-4]

[2, 3, 4, 5, 6]

In [22]:
ma_liste[::2]

[1, 3, 5, 7, 'hello']

In [23]:
ma_liste[1::2]

[2, 4, 6, 8, 10.5]

In [24]:
ma_liste.append(2)

In [25]:
print(ma_liste)

[1, 2, 3, 4, 5, 6, 7, 8, 'hello', 10.5, 2]


In [26]:
ma_liste.insert(5,"nouvelle")

In [27]:
print(ma_liste)

[1, 2, 3, 4, 5, 'nouvelle', 6, 7, 8, 'hello', 10.5, 2]


In [28]:
ma_liste[0]="a"

In [29]:
print(ma_liste)

['a', 2, 3, 4, 5, 'nouvelle', 6, 7, 8, 'hello', 10.5, 2]


In [30]:
ma_liste[3:5]=[8,10]

In [31]:
print(ma_liste)

['a', 2, 3, 8, 10, 'nouvelle', 6, 7, 8, 'hello', 10.5, 2]


In [32]:
ma_liste[0:2]=[]
print(ma_liste)

[3, 8, 10, 'nouvelle', 6, 7, 8, 'hello', 10.5, 2]


In [33]:
del ma_liste[3]

In [34]:
print(ma_liste)

[3, 8, 10, 6, 7, 8, 'hello', 10.5, 2]


In [43]:
ma_liste1=[1,2,3,4,5]

In [44]:
ma_liste2=[6,7,8,9,10]

In [45]:
ma_liste3=ma_liste1+ma_liste2

In [46]:
ma_liste3

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [47]:
sum(ma_liste3)

55

In [48]:
len(ma_liste3)

10

In [15]:
ma_liste=[5,6,1,2,5,6,6]

In [50]:
ma_liste

[5, 6, 1, 2, 5, 6, 6]

In [51]:
ma_liste.count(6)

3

In [52]:
ma_liste.sort()

In [53]:
ma_liste

[1, 2, 5, 5, 6, 6, 6]

In [16]:
ma_liste.reverse()

In [17]:
ma_liste

[6, 6, 5, 2, 1, 6, 5]

In [56]:
min(ma_liste)

1

In [57]:
max(ma_liste)

6

In [58]:
tuple1=(1,2,3,4,5)

In [59]:
tuple1

(1, 2, 3, 4, 5)

In [60]:
tuple1[0]=0

TypeError: 'tuple' object does not support item assignment

In [61]:
tuple1[1]

2

In [30]:
mes_notes=[19,7,15,9,10,6,18,10,16,14,13,10,2,20,17,8,12,10,11,4]

In [31]:
mes_notes

[19, 7, 15, 9, 10, 6, 18, 10, 16, 14, 13, 10, 2, 20, 17, 8, 12, 10, 11, 4]

In [32]:
import numpy
moyenne_generale=numpy.mean(mes_notes)

In [33]:
moyenne_generale

11.55

In [34]:
min(mes_notes)

2

In [35]:
max(mes_notes)

20

In [36]:
mes_notes.sort()

In [37]:
mes_notes

[2, 4, 6, 7, 8, 9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [38]:
mes_notes.reverse()

In [39]:
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 2]

In [40]:
mes_notes.sort()

In [41]:
mes_notes

[2, 4, 6, 7, 8, 9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [44]:
help(mes_notes.sort)

Help on built-in function sort:

sort(*, key=None, reverse=False) method of builtins.list instance
    Stable sort *IN PLACE*.



In [45]:
mes_notes.sort(reverse=True)

In [46]:
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 2]

In [48]:
mes_notes[19]=6

In [49]:
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 6]

In [50]:
mes_notes.count(10)

4

In [51]:
mes_notes_array=numpy.asarray(mes_notes)

In [52]:
mes_notes_array

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10,  9,  8,  7,
        6,  4,  6])

In [53]:
mes_notes_array[mes_notes_array>10]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [54]:
mes_notes_array>10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [55]:
len(mes_notes_array[mes_notes_array>10])

10

In [56]:
mes_notes[mes_notes>10]

TypeError: '>' not supported between instances of 'list' and 'int'